#!/usr/bin/env sh

# Pre-push hook that blocks WIP ("work in progress") commits.
#
# Exits with a nonzero status if any outbound commits are WIPs and zero
# otherwise. A commit is considered a WIP if its commit message begins with
# "FIXUP", "NOCOMMIT", "REWORD", "SQUASH", or "WIP" (matched
# case-sensitively). These can be enclosed in braces ("{WIP}"), brackets
# ("[WIP]"), or parentheses ("(WIP)"). They can also be bare ("WIP") if they
# are not immediately followed by a letter.
#
# See also: https://git-scm.com/docs/githooks/2.24.0#_pre_push


exec >&2

# Git prepends its exec directory to PATH, so this just works.
. git-sh-setup

keywords='FIXUP|NOCOMMIT|REWORD|SQUASH|WIP'

status=0
while read -r local_ref local_sha1 remote_ref remote_sha1
do
    if [ "$local_sha1" = 0000000000000000000000000000000000000000 ]; then
        # Deleting a remote ref doesn't push any commits.
        continue
    elif [ "$remote_sha1" = 0000000000000000000000000000000000000000 ]; then
        # Creating new remote ref.
        range=$local_sha1
    else
        # Updating existing remote ref.
        range=$remote_sha1..$local_sha1
    fi

    # TODO Print with the right colors at the right time.
    git rev-list --extended-regexp --grep="^($keywords)([^[:alpha:]]|$)" \
        --grep="^\(($keywords))|^\{($keywords)}|^\[($keywords)]" \
        --pretty='%h %s' "$range" \
    | {
        # Discard the first "commit [full SHA1]" line.
        if read -r; then
            # Print a blank line between ranges.
            if [ "$status" -ne 0 ]; then
                echo
            fi
            printf '%s: blocked push to %s\n' "${0##*/}" "$remote_ref"
            printf '%s: WIP commits in %s:\n' "${0##*/}" "$local_ref"

            # Only the "oneline" pretty-format omits "commit [full SHA1]"
            # lines, so we have to discard them ourselves.
            sed '/^commit /d'

            # https://mywiki.wooledge.org/BashFAQ/024 - The enclosing `if` may
            # run in a subshell, so use the exit status of the pipeline to set
            # 'status' on the outside.
            false
        fi
    } || status=1
done
exit $status
